#!/usr/bin/env python3
"""
Run the roll-math spec outside Roblox.

The data modules (Config, Rarities, Cards, RollLogic) are pure Luau - they touch
Color3, Vector3 and Random but never an Instance - so they can run in the
standalone Luau interpreter with those globals stubbed.

Usage:
    python3 roblox/tests/run.py [path-to-luau-binary]

Get the interpreter from https://github.com/luau-lang/luau/releases
(the `luau` binary inside luau-ubuntu.zip / luau-macos.zip / luau-windows.zip).
"""

import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
MODULES_DIR = os.path.join(HERE, "..", "src", "ReplicatedStorage", "CardSystem")
SPEC = os.path.join(HERE, "roll_logic_spec.luau")
LOAD_ORDER = ["Config", "Rarities", "Categories", "Cards", "RollLogic"]

PRELUDE = """-- generated by roblox/tests/run.py: stubs for the Roblox globals used here
local Color3 = { fromRGB = function(r, g, b) return { R = r, G = g, B = b } end }
local Vector3 = { new = function(x, y, z) return { X = x, Y = y, Z = z } end }
-- Enum.Anything.Anything resolves to a named placeholder.
local Enum = setmetatable({}, { __index = function(_, enumName)
\treturn setmetatable({}, { __index = function(_, itemName)
\t\treturn { Name = itemName, EnumType = enumName }
\tend })
end })
local Random = { new = function()
\treturn {
\t\tNextNumber = function(self, a, b) return a + math.random() * (b - a) end,
\t\tNextInteger = function(self, a, b) return math.random(a, b) end,
\t}
end }
local MODS = {}
local function require(m) return m end
"""


def build_harness() -> str:
    parts = [PRELUDE]
    for name in LOAD_ORDER:
        with open(os.path.join(MODULES_DIR, name + ".luau"), encoding="utf-8") as handle:
            source = handle.read().replace("--!strict", "")
        parts.append(
            f"MODS.{name} = (function()\n\tlocal script = {{ Parent = MODS }}\n{source}\nend)()\n"
        )
    with open(SPEC, encoding="utf-8") as handle:
        parts.append(handle.read())
    return "".join(parts)


def main() -> int:
    luau = sys.argv[1] if len(sys.argv) > 1 else shutil.which("luau")
    if not luau:
        print("luau interpreter not found; pass its path as the first argument", file=sys.stderr)
        return 2

    with tempfile.NamedTemporaryFile("w", suffix=".luau", delete=False, encoding="utf-8") as tmp:
        tmp.write(build_harness())
        harness = tmp.name

    try:
        return subprocess.call([luau, harness])
    finally:
        os.unlink(harness)


if __name__ == "__main__":
    raise SystemExit(main())
